### ISSUE TITLE
Original and translation side by side

### ISSUE THREAD

**Issue by Poyeyo** [azu/mu-epub-reader#2]
Hi, how hard is to implement this?

![image](https://user-images.githubusercontent.com/2475920/88408856-bba40380-cd99-11ea-955d-4d21fe628770.png)

It would be amazing for learning a language.

**Comment by azu** [comment]
It is difficult that current implementation just uses google translation toolbar.
https://github.com/azu/mu-epub-reader/blob/c52823ae22ee3292c265ab5aa75079af4bb33881/reader/index.html#L67

Probably, we need to use [Google Translation API](https://cloud.google.com/translate/)(paid) for implementing this feature.
